alpha: 0.4
answer_list: /home/coder/projects/Med-VQA/data/testset.json
batch_size_test: 16
batch_size_train: 8
bert_config: configs/config_bert.json
distill: true
eos: '[SEP]'
image_res: 384
k_test: 128
optimizer: {lr: 1e-05, opt: adamW, weight_decay: 0.02}
schedular: {cooldown_epochs: 0, decay_rate: 1, epochs: 10, lr: 2e-05, min_lr: 1e-06,
  sched: cosine, warmup_epochs: 4, warmup_lr: 1e-05}
test_file: [/home/coder/projects/Med-VQA/data/testset.json]
train_file: [/home/coder/projects/Med-VQA/data/trainset.json]
vg_root: ../data/VG/VG_100K/
vqa_root: /home/coder/projects/Med-VQA/data
warm_up: true
