train_file: [
            '/home/coder/projects/Med-VQA/data_SLAKE/trainset.json'
            #  '../data/json_down/vqa_val.json',   
             ]
             
test_file: ['/home/coder/projects/Med-VQA/data_SLAKE/testset.json']
answer_list: '/home/coder/projects/Med-VQA/data_SLAKE/testset.json'

vqa_root: '/home/coder/projects/Med-VQA/data_SLAKE' #train2014/
vg_root: '../data/VG/VG_100K/'  #image/

image_res: 384
# alter by hxj
batch_size_train: 16 
batch_size_test: 16 
k_test: 128

alpha: 0.4
distill: True
warm_up: True

eos: '[SEP]'

bert_config: 'configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}

## alter by hxj
schedular: {sched: cosine, lr: 2e-5, epochs: 15, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}

dataset: 'SLAKE'





