train_file: [
            '/home/coder/projects/SystemDataset/data_OVQA_as_RAD/trainset.json'
            #  '../data/json_down/vqa_val.json',   
             ]
             
test_file: ['/home/coder/projects/SystemDataset/data_OVQA_as_RAD/testset.json']
answer_list: '/home/coder/projects/SystemDataset/data_OVQA_as_RAD/testset.json'

vqa_root: '/home/coder/projects/SystemDataset/data_OVQA_as_RAD' #train2014/

## alter by hxj
vg_root: '/home/coder/projects/SystemDataset/data_OVQA_as_RAD/images/'  #image/

image_res: 384
# alter by hxj
batch_size_train: 4 
batch_size_test: 4 
k_test: 128

alpha: 0.4
distill: True
warm_up: True

eos: '[SEP]'

bert_config: 'configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}

## alter by hxj
schedular: {sched: cosine, lr: 2e-5, epochs: 13, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}

dataset: 'OVQA'





